config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :tweets do
    resources :replies, only: [:create,:destroy]

    member do
      get 'like', to: 'tweets#like', as: 'like'
      get 'unlike', to: 'tweets#unlike', as: 'unlike'
    end
  end

  # DISPLAY USER DASHBOARD
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'

  # FOLLOW USER ROUTE [REQUIRED PARAMETER=USERNAME]
  get '/:username/follow', to: 'pages#follow', as: 'follow_user'

  # UNFOLLOW USER ROUTE [REQUIRED PARAMETER=USERNAME]
  get '/:username/unfollow', to: 'pages#unfollow', as: 'unfollow_user'

  # DISPLAY USER FOLLOWERS [REQUIRED PARAMETER=USERNAME]
  get '/:username/followers', to: 'pages#followers', as: 'followers'

  # DISPLAY USER FOLLOWINGS [REQUIRED PARAMETER=USERNAME]
  get '/:username/followings', to: 'pages#followings', as: 'followings'

  # USERPAGE USER ROUTE [REQUIRED PARAMETER=USERNAME]
  get '/:username', to: 'pages#userpage', as: 'userpage'

  # ROOT PATH TO WELCOME PAGE
  root to: "pages#welcome"
  
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :replies

  acts_as_likeable
  
  has_attached_file :image, styles: { medium: "550x550>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_attached_file :avatar, styles: { medium: "300x300#", thumb: "40x40#" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	has_many :tweets
	has_many :replies

	acts_as_followable
	acts_as_follower
	acts_as_liker

    def self.find_for_database_authentication(warden_conditions)
		conditions = warden_conditions.dup
		if login = conditions.delete(:login)
			where(conditions).where(["lower(username) = lower(:value) OR lower(email) = lower(:value)", { :value => login }]).first
		elsif conditions.has_key?(:username) || conditions.has_key?(:email)
			where(conditions.to_hash).first
		end
	end

	validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

	validates :username,
		:presence => true,
		:uniqueness => {
		:case_sensitive => false
		} # etc.
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :avatar, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :authenticate_user!, except:[:welcome]

  def welcome
  end

  def dashboard
    # Display dashboard

    @tweets = Tweet.all.order(created_at: :desc)
  end

  def follow
    # Follow user
    @user = User.find_by(username: params[:username])
    if !@user.nil?
      current_user.follow!(@user)
      respond_to do |format|
        format.html{ redirect_to :back}
        format.js{}
      end
    end
  end

  def unfollow
    # Unfollow user
    @user = User.find_by(username: params[:username])
    if !@user.nil?
      current_user.unfollow!(@user)
      respond_to do |format|
        format.html{ redirect_to :back}
        format.js{}
      end
    end
  end

  def followers
    # Display user's followers
    @user = User.find_by(username: params[:username])
    if !@user.nil?
      @users = @user.followers(User)
    end
  end

  def followings
    # Display user's followings
    @user = User.find_by(username: params[:username])
    if !@user.nil?
      @users = @user.followings(User)
    end
  end

  def userpage
    @user = User.find_by(username: params[:username])
    @tweets = @user.tweets.order(created_at: :desc)
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @reply = Reply.new(reply_params)
    @reply.user_id = current_user.id
    @reply.tweet_id = @tweet.tweet_id
    @reply.save
    respond_to do |format|
      format.html{redirect_to tweet_path(@tweet)}
      format.js{}
    end
  end

  def destroy
    @tweet = Tweet.find(params[:tweet_id])
    @tweet.destroy
    respond_to do |format|
      format.html{ redirect_to :back }
      format.js{}
    end
  end


end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tags = @tweet.content.scan(/#\w+/).flatten
    @tweet.user_id = current_user.id
    @tweet.save
    respond_to do |format|
      format.html{ redirect_to tweet_path(@tweet) }
      format.js{}
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    @tweet.update(tweet_params)
    @tweet.save
    respond_to do |format|
      format.html{ redirect_to tweet_path(@tweet) }
      format.js{}
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    respond_to do |format|
      format.html{ redirect_to :back }
      format.js{}
    end
  end

  def like
    @tweet = Tweet.find(params[:id])
    current_user.like!(@tweet)
    respond_to do |format|
      format.html{ redirect_to :back }
      format.js{}
    end
  end  

  def unlike
    @tweet = Tweet.find(params[:id])
    current_user.unlike!(@tweet)
    respond_to do |format|
      format.html{ redirect_to :back }
      format.js{}
    end
  end

  private
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "TClone", root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if !user_signed_in? %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <% else %>
        <li><%= link_to "Home", dashboard_path %></li>
        <li><%= link_to "Compose tweet", new_tweet_path %></li>
        <li><%= link_to "#{current_user.username}", userpage_path(current_user.username) %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% end %>
    </ul>
  </div>
</nav>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/pages/dashboard.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="tweets">
			<%= render partial: 'tweets/tweet', collection: @tweets %>
		</div>
	</div>
</div>

app/views/pages/userpage.html.erb
<div class="row">
	<div class="col-md-3">
		<div class="usercard_vr">
			<%= image_tag(@user.avatar.url(:medium),class: 'img-rounded img-responsive') %>
			<span class="username">
				<%= @user.username %>
			</span>
			<span class="user-actions">
				<% if user_signed_in? %>
					<% if current_user.id != @user.id %>
						<% if current_user.follows?(@user) %>
							<%= link_to "Following", unfollow_user_path(@user.username), class: 'unfollow-btn' %>
						<% else %>
							<%= link_to "Follow", follow_user_path(@user.username), class: 'follow-btn' %>
						<% end %>
					<% end %>
				<% else %>
					<%= link_to "Follow", follow_user_path(@user.id), class: 'follow-btn' %>
				<% end %>
			</span>
		</div>
	</div>
	<div class="col-md-6">
		<div class="tweets">
			<%= render partial: 'tweets/tweet', collection: @tweets %>
		</div>
	</div>
</div>

app/views/pages/welcome.html.erb
Pages#welcome

app/views/tweets/_form.html.erb
<%= simple_form_for @tweet, html:{multipart: true}, validate: true do |f| %>
	
	<div class="form-group">
		<%= f.input :content, label: false, input_html:{placeholder: "Just Say It..."} %>
	</div>
	<div class="form-action">
		<%= f.submit "Post", class: 'btn btn-primary post_tweet_btn' %>
	</div>

<% end %>

app/views/tweets/_tweet.html.erb
<div class="tweet">
  <div class="media tweet-header">
    <div class="media-left">
      <%= image_tag(tweet.user.avatar.url(:thumb),class: 'img-rounded') %>
    </div>
    <div class="media-body">
      <%= link_to tweet.user.username, userpage_path(tweet.user.username) %>
    </div>
  </div>
  <div class="tweet-body">
    <p>
      <%= tweet.content %>
    </p>
  </div>
  <div class="tweet-footer">
    <div class="row tweet-actions">
      <span class="like">
        <% if user_signed_in? %>
          <% if current_user.likes?(tweet) %>
            <%= link_to fa_icon('heart lg'), unlike_tweet_path(tweet.id), class: 'unlike-btn' %>
          <% else %>
            <%= link_to fa_icon('heart-o lg'), like_tweet_path(tweet.id) %>
          <% end %>
        <% else %>
          <%= link_to fa_icon('heart-o lg'), like_tweet_path(tweet.id) %>
        <% end %>
      </span>
      <span class="reply">
        <%= link_to fa_icon('comment-o lg') %>
      </span>
      <span class="counter"></span>
    </div>

    <div class="reply-form">
      
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="new_tweet_form">
			<h4 class="form-heading">Compose tweet</h4>
			<%= render partial: 'form' %>
		</div>
	</div>		
</div>